import type { Metadata } from 'next';
import './globals.css';
import { Layout } from '@repo/ui';
import React from 'react';

export const metadata: Metadata = {
  title: 'Hackarena',
  description: 'Generated by create next app',
};

const navItems = [
  {
    label: 'Wydarzenia',
    href: '/wydarzenia',
  },
  {
    label: 'Kontakt',
    href: '/kontakt',
  },
  {
    label: 'Konto',
    href: '/konto',
    highlight: true,
  },
];

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return <Layout navItems={navItems}>{children}</Layout>;
}
